/// Demo data for GabonConnect preview
/// Real Gabon marketplace data
library;

final Map<String, dynamic> gabonDemoData = {
  'users': [
    {
      'id': '1',
      'email': 'jean.mbadinga@gmail.com',
      'full_name': 'Jean Mbadinga',
      'phone_number': '+241612345678',
      'avatar_url': 'https://i.pravatar.cc/150?img=1',
      'bio': 'Électricien professionnel à Libreville',
      'verified': true,
      'rating': 4.8,
      'reviews_count': 142,
    },
    {
      'id': '2',
      'email': 'marie.ondoua@gmail.com',
      'full_name': 'Marie Ondoua',
      'phone_number': '+241614567890',
      'avatar_url': 'https://i.pravatar.cc/150?img=2',
      'bio': 'Experte en nettoyage résidentiel',
      'verified': true,
      'rating': 4.9,
      'reviews_count': 156,
    },
    {
      'id': '3',
      'email': 'claude.nkomo@gmail.com',
      'full_name': 'Claude Nkomo',
      'phone_number': '+241616789012',
      'avatar_url': 'https://i.pravatar.cc/150?img=3',
      'bio': 'Réparateur informatique certifié',
      'verified': true,
      'rating': 4.7,
      'reviews_count': 56,
    },
    {
      'id': '4',
      'email': 'sophie.ivie@gmail.com',
      'full_name': 'Sophie Ivié',
      'phone_number': '+241618901234',
      'avatar_url': 'https://i.pravatar.cc/150?img=4',
      'bio': 'Vendeuse de vêtements branché',
      'verified': true,
      'rating': 4.8,
      'reviews_count': 89,
    },
    {
      'id': '5',
      'email': 'pierre.mboumbou@gmail.com',
      'full_name': 'Pierre Mboumbou',
      'phone_number': '+241610234567',
      'avatar_url': 'https://i.pravatar.cc/150?img=5',
      'bio': 'Menuisier & ébéniste',
      'verified': true,
      'rating': 4.6,
      'reviews_count': 43,
    },
  ],
  'services': [
    {
      'id': '1',
      'provider_id': '1',
      'provider_name': 'Jean Mbadinga',
      'title': '⚡ Installation électrique',
      'description': 'Installation complète de circuits électriques, tableau, etc.',
      'price': 50000,
      'category': 'électricité',
      'rating': 4.8,
      'reviews_count': 142,
      'icon': '⚡',
    },
    {
      'id': '2',
      'provider_id': '1',
      'provider_name': 'Jean Mbadinga',
      'title': '⚡ Réparation électrique',
      'description': 'Dépannage électrique urgent - 24h/24',
      'price': 25000,
      'category': 'électricité',
      'rating': 4.9,
      'reviews_count': 89,
      'icon': '⚡',
    },
    {
      'id': '3',
      'provider_id': '2',
      'provider_name': 'Marie Ondoua',
      'title': '🏡 Nettoyage maison',
      'description': 'Nettoyage complet résidentiel',
      'price': 30000,
      'category': 'nettoyage',
      'rating': 4.9,
      'reviews_count': 156,
      'icon': '🏡',
    },
    {
      'id': '4',
      'provider_id': '2',
      'provider_name': 'Marie Ondoua',
      'title': '🏢 Nettoyage bureau',
      'description': 'Nettoyage et maintenance bureaux',
      'price': 45000,
      'category': 'nettoyage',
      'rating': 4.7,
      'reviews_count': 72,
      'icon': '🏢',
    },
    {
      'id': '5',
      'provider_id': '3',
      'provider_name': 'Claude Nkomo',
      'title': '💻 Réparation ordinateur',
      'description': 'Diagnostic, logiciels, hardware',
      'price': 25000,
      'category': 'informatique',
      'rating': 4.7,
      'reviews_count': 56,
      'icon': '💻',
    },
    {
      'id': '6',
      'provider_id': '3',
      'provider_name': 'Claude Nkomo',
      'title': '🌐 Installation réseau',
      'description': 'Mise en place WiFi, câblage réseau',
      'price': 75000,
      'category': 'informatique',
      'rating': 4.8,
      'reviews_count': 34,
      'icon': '🌐',
    },
    {
      'id': '7',
      'provider_id': '5',
      'provider_name': 'Pierre Mboumbou',
      'title': '🪑 Menuiserie',
      'description': 'Meubles, portes, escaliers custom',
      'price': 60000,
      'category': 'menuiserie',
      'rating': 4.6,
      'reviews_count': 43,
      'icon': '🪑',
    },
  ],
  'products': [
    {
      'id': '1',
      'seller_id': '4',
      'seller_name': 'Sophie Ivié',
      'title': '📱 iPhone 14 Pro',
      'description': 'Excellent état, complet avec accessoires',
      'price': 850000,
      'category': 'électronique',
      'rating': 4.9,
      'icon': '📱',
    },
    {
      'id': '2',
      'seller_id': '4',
      'seller_name': 'Sophie Ivié',
      'title': '👕 Vêtements femme collection été',
      'description': 'Robe, chemise, short tendance',
      'price': 45000,
      'category': 'mode',
      'rating': 4.8,
      'icon': '👕',
    },
    {
      'id': '3',
      'seller_id': '5',
      'seller_name': 'Pierre Mboumbou',
      'title': '🪑 Mobilier bureau',
      'description': 'Bureau, chaise, étagère occasion bon état',
      'price': 150000,
      'category': 'mobilier',
      'rating': 4.7,
      'icon': '🪑',
    },
    {
      'id': '4',
      'seller_id': '4',
      'seller_name': 'Sophie Ivié',
      'title': '👟 Chaussures Nike',
      'description': 'Baskets neuves, taille 42',
      'price': 75000,
      'category': 'mode',
      'rating': 4.8,
      'icon': '👟',
    },
    {
      'id': '5',
      'seller_id': '3',
      'seller_name': 'Claude Nkomo',
      'title': '💻 Laptop gaming',
      'description': 'RTX 3060, i7, 16GB RAM, comme neuf',
      'price': 1200000,
      'category': 'électronique',
      'rating': 4.9,
      'icon': '💻',
    },
  ],
  'messages': [
    {
      'id': '1',
      'sender_name': 'Jean Client',
      'receiver_name': 'Jean Mbadinga',
      'content': 'Bonjour, j\'ai besoin d\'une réparation électrique urgent. Pouvez-vous venir demain?',
      'read': false,
      'timestamp': 'Il y a 2 minutes',
    },
    {
      'id': '2',
      'sender_name': 'Jean Mbadinga',
      'receiver_name': 'Jean Client',
      'content': 'Oui, bien sûr! Je peux venir entre 10h et 12h demain. C\'est pour quel problème?',
      'read': true,
      'timestamp': 'Il y a 5 minutes',
    },
    {
      'id': '3',
      'sender_name': 'Alice Dupont',
      'receiver_name': 'Sophie Ivié',
      'content': 'L\'iPhone est encore disponible? Quel est votre dernier prix?',
      'read': false,
      'timestamp': 'Il y a 10 minutes',
    },
    {
      'id': '4',
      'sender_name': 'Sophie Ivié',
      'receiver_name': 'Alice Dupont',
      'content': 'Oui! Prix ferme 850k. Je peux vous le montrer ce weekend?',
      'read': true,
      'timestamp': 'Il y a 15 minutes',
    },
  ],
  'reviews': [
    {
      'reviewer_name': 'Jean Client',
      'reviewee_name': 'Jean Mbadinga',
      'rating': 5,
      'comment': 'Excellent travail! Très professionnel et rapide. Je recommande vivement!',
      'tags': ['professionnel', 'rapide', 'fiable'],
    },
    {
      'reviewer_name': 'Alice Dupont',
      'reviewee_name': 'Marie Ondoua',
      'rating': 5,
      'comment': 'Nettoyage impeccable! Ma maison brille comme neuve. Merci!',
      'tags': ['excellent', 'détail', 'courtois'],
    },
    {
      'reviewer_name': 'Jean Client',
      'reviewee_name': 'Claude Nkomo',
      'rating': 4,
      'comment': 'Bon diagnostic. Dommage qu\'il n\'avait pas la pièce pour réparation directe.',
      'tags': ['honnête', 'compétent'],
    },
  ],
  'statistics': {
    'total_users': 8,
    'verified_users': 6,
    'total_services': 9,
    'total_products': 5,
    'total_messages': 4,
    'avg_rating': 4.76,
  },
};
